services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.19-ubi8
    container_name: crypto-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - crypto_network

  influxdb:
    image: influxdb:2.7.1
    container_name: crypto-influxdb
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_RETENTION: 104w
    ports:
      - 8086:8086
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge