services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.19-ubi8
    container_name: crypto-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin_password
      MONGO_INITDB_DATABASE: agent_crypto_db
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - crypto_network

  influxdb:
    image: influxdb:3-core
    container_name: crypto-influxdb
    restart: always
    ports:
      - 8181:8181 
    volumes:
      - ./influxdb_data:/var/lib/influxdb3
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge