services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0.19-ubi8
    container_name: crypto-mongodb
    restart: always
    environment:
      MONGODB_INITDB_ROOT_USERNAME: admin
      MONGODB_INITDB_ROOT_PASSWORD: admin_password
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - crypto_network

  influxdb:
    image: influxdb:2.7.1
    container_name: crypto-influxdb
    restart: always
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin_password
      - DOCKER_INFLUXDB_INIT_ORG=crypto_org
      - DOCKER_INFLUXDB_INIT_BUCKET=crypto_price
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=admin_token
    ports:
      - 8086:8086
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge